# Generated by Django 5.1.1 on 2024-10-11 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('Mon', 'Lunes'), ('Tue', 'Martes'), ('Wed', 'Miércoles'), ('Thu', 'Jueves'), ('Fri', 'Viernes'), ('Sat', 'Sábado'), ('Sun', 'Domingo')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tech', 'Tecnología'), ('lang', 'Idiomas'), ('scho', 'Materias escolares'), ('art', 'Arte'), ('cook', 'Cocina'), ('DIY', 'Manualidades'), ('bsns', 'Negocios'), ('oth', 'Otros')], max_length=4)),
                ('availability', models.ManyToManyField(to='EduPlatform.availability')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.ManyToManyField(to='EduPlatform.interest')),
                ('list_of_classes', models.ManyToManyField(to='EduPlatform.classes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', models.IntegerField()),
                ('educational_level', models.CharField(choices=[('basic', 'Bachillerato'), ('technical', 'Técnica'), ('technological', 'Tecnológico'), ('BD', 'Profesional'), ('PD', 'Posgrado')], max_length=13)),
                ('bio', models.TextField()),
                ('list_of_classes', models.ManyToManyField(to='EduPlatform.classes')),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EduPlatform.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EduPlatform.teacherprofile'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Profesor'), ('student', 'Estudiante')], max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
