# Generated by Django 5.1.1 on 2024-11-09 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduPlatform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='EduPlatform.teacherprofile'),
        ),
    ]
