# Generated by Django 5.1.1 on 2024-10-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduPlatform', '0002_location_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='interests',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
