# Generated by Django 5.1.1 on 2024-11-09 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduPlatform', '0002_alter_classes_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='teacher',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='EduPlatform.teacherprofile'),
            preserve_default=False,
        ),
    ]
