# Generated by Django 5.1.1 on 2024-10-28 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduPlatform', '0003_remove_studentprofile_interests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='is_online',
        ),
    ]
