# Generated by Django 5.1.1 on 2024-11-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduPlatform', '0004_remove_location_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
