# Generated by Django 5.1.1 on 2024-11-19 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduPlatform', '0005_classrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EduPlatform.location'),
        ),
    ]
