# Generated by Django 5.1.1 on 2024-11-07 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduPlatform', '0005_classes_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='availability',
        ),
        migrations.AddField(
            model_name='availability',
            name='class_obj',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='EduPlatform.classes'),
            preserve_default=False,
        ),
    ]
