# Generated by Django 5.1.1 on 2024-11-08 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduPlatform', '0006_remove_classes_availability_availability_class_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EduPlatform.location'),
        ),
    ]
